# vim: ft=yaml
os:
  - linux
  - osx

language: bash

sudo: required

env:
  - TRAVIS_BASH_VERSION="4.1" TRAVIS_ZSH_VERSION="5.0.0" TRAVIS_FISH_VERSION="2.2.0" TRAVIS_GIT_VERSION="1.8.0"

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tests/test-utils/installs/install-linux-deps.sh; fi;
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./tests/test-utils/installs/install-osx-deps.sh; fi;

install:
  - pip install --user pearlcli
  - export PATH="~/.local/bin:$PATH"
  - pearl init
  - echo "PEARL_PACKAGES['test'] = {'url': '${PWD}'}" >> ~/.config/pearl/pearl.conf
  - source ~/.bashrc

script:
  - bash ./tests/test-utils/integ-tests/default-integ-tests.sh
